name: silverbullet

services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet:latest
    container_name: silverbullet
    restart: unless-stopped
    user: 1000:1000
    environment:
      SB_USER: ${SB_USER_USER}:${SB_USER_PASSWORD}
    volumes:
      - /mnt/notes:/space
    ports:
      - 3001:3000
