name: explo

services:
  explo:
    image: ghcr.io/lumepart/explo:latest
    container_name: music_explo
    restart: unless-stopped
    volumes:
      - ./.env:/opt/explo/.env
      - /mnt/music/explo:/data 
    environment:
      TZ: 'Europe/Prague'
      WEEKLY_EXPLORATION_SCHEDULE: '15 2 * * 1'
      WEEKLY_EXPLORATION_FLAGS: ''
      WEEKLY_JAMS_SCHEDULE: '15 1 * * 1'
      WEEKLY_JAMS_FLAGS: '--playlist=weekly-jams --download-mode=normal'
      DAILY_JAMS_SCHEDULE: '15 0 * * *'
      DAILY_JAMS_FLAGS: '--playlist=daily-jams --download-mode=normal'
      LISTENBRAINZ_USER: ${LISTENBRAINZ_USER} # these must be in .env because godotenv bruh
      EXPLO_SYSTEM: ${EXPLO_SYSTEM}
      SYSTEM_URL: ${SYSTEM_URL}
      SYSTEM_USERNAME: ${SYSTEM_USERNAME}
      SYSTEM_PASSWORD: ${SYSTEM_PASSWORD}
      ADMIN_SYSTEM_USERNAME: ${ADMIN_SYSTEM_USERNAME}
      ADMIN_SYSTEM_PASSWORD: ${ADMIN_SYSTEM_PASSWORD}
    labels: # TODO: using ofelia until theres native solution
      ofelia.enabled: "true"
      ofelia.job-exec.explo-chown.schedule: "45 2 * * *"
      ofelia.job-exec.explo-chown.command: "chown 1000:1000 -R /data"

  ofelia:
    image: mcuadros/ofelia:latest
    container_name: music_explo_ofelia
    depends_on:
      - explo
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
