name: caddy

services:
  caddy:
    build: ./config
    container_name: caddy
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./config:/etc/caddy
      - /mnt/data/caddy/data:/data
      - /mnt/data/caddy/config:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
      PORKBUN_API_SECRET_KEY: ${PORKBUN_API_SECRET_KEY}
