name: caddy

services:
  caddy:
    build: ./config
    container_name: caddy
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./config:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env.secret

volumes:
  caddy_data:
  caddy_config:
