name: caddy

services:
  caddy:
    container_name: caddy
    # image: caddy:latest
    image: ghcr.io/major/caddy:main
    # image: serfriz/caddy-porkbun-dockerproxy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./config:/etc/caddy
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env.secret
