- name: home
  head-widgets:
    - type: search
      hide-header: true
      search-engine: google
      autofocus: true
      bangs:
        - title: youtube
          shortcut: "!yt"
          url: https://www.youtube.com/results?search_query={QUERY}
  columns:
    - size: small
      widgets:
        - type: clock
          hide-header: true
        - type: weather
          hide-header: true
          hour-format: 24h
          location: Ostrava, Czechia
        - type: calendar
          hide-header: true
    - size: small
      widgets:
        - type: server-stats
          hide-header: true
          servers:
            - type: local
              name: apps
              mountpoints:
                "/":
                  name: root
                  hide: false
                "/mnt/data":
                  name: data
                  hide: false
        - type: monitor
          cache: 1m
          hide-header: true
          sites:
            - title: pihole
              url: https://pihole.tux.vuxnq.me/admin
              icon: di:pi-hole
              same-tab: true
        - type: dns-stats
          hide-header: true
          service: pihole-v6
          url: https://pihole.tux.vuxnq.me
          password: ${PIHOLE_PASSWORD}
          hour-format: 24h
        $include: home.lastfm.yml
    - size: full
      widgets:
        $include: home.bookmarks.yml
        $include: home.docker-containers.yml
