apps_dir: /opt/apps
apps_services:
  - caddy
  - dufs
  - glance
  - immich
  - syncthing

apps_dirs:
  - path: /mnt/data/dufs/shared
  - path: /mnt/data/syncthing
  - path: /mnt/data/syncthing/config
