---

- name: add docker apt key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: add docker apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
    state: present

- name: install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present

- name: cap docker container log sizes
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      { "log-driver": "json-file", "log-opts": { "max-size": "20m", "max-file": "3" } }
    mode: "0644"
  notify: restart docker

- name: ensure docker is enabled and running
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
