name: gatus

services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8081:8080
    volumes:
      - ./config:/config
      - /mnt/data/gatus/data:/data
    environment:
        DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
        BACKUP_ENDPOINT_TOKEN: ${BACKUP_ENDPOINT_TOKEN}
