name: pihole

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: sheol
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8053:80/tcp
    environment:
      TZ: Europe/Prague
      FTLCONF_dns_listeningMode: ALL
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
    volumes:
      - ./data:/etc/pihole
    restart: unless-stopped
