name: music

services:
  gonic:
    image: sentriz/gonic:latest
    container_name: music_gonic
    user: 1000:1000
    ports:
      - 4747:80
    environment:
      GONIC_SCAN_INTERVAL: 60
      GONIC_CACHE_PATH: /data/cache
    volumes:
      - ./data/gonic:/data
      - /mnt/music/library:/music:ro
      - /mnt/music/podcasts:/podcasts
      - /mnt/music/playlists:/playlists
    restart: unless-stopped

  wrtag:
    image: sentriz/wrtag:latest
    container_name: music_wrtag
    environment:
      PUID: 1000
      PGID: 1000
      WRTAG_WEB_LISTEN_ADDR: ':7373'
      WRTAG_WEB_DB_PATH: /data/wrtag.db
      WRTAG_PATH_FORMAT: '/music/{{ artists .Release.Artists | join "; " | safepath }}/{{ .Release.Title | safepath }}/{{ pad0 2 .TrackNum }} {{ .Track.Title | safepath }}{{ .Ext }}'
      WRTAG_ADDON: 'replaygain,musicdesc,lyrics lrclib genius musixmatch,subproc metadata image-write <cover> -- <files>'
      WRTAG_RESEARCH_LINK: 'musicbrainz https://musicbrainz.org/taglookup?tag-lookup.artist={{ .Artist | urlquery }}&tag-lookup.release={{ .Album | urlquery }},spotify https://open.spotify.com/search/{{ printf "%s %s" .Artist .Album | urlquery }},tidal https://tidal.com/search?q={{ printf "%s %s" .Artist .Album | urlquery }},bandcamp https://bandcamp.com/search?q={{ printf "%s %s" .Artist .Album | urlquery }},apple-music https://music.apple.com/search?term={{ printf "%s %s" .Artist .Album | urlquery }},soundcloud https://soundcloud.com/search?q={{ printf "%s %s" .Artist .Album | urlquery }},lastfm https://www.last.fm/search?q={{ printf "%s %s" .Artist .Album | urlquery }},harmony https://harmony.pulsewidth.org.uk/release?url=&gtin={{ .Barcode | urlquery }}&region=&deezer=&itunes=&spotify=&tidal=&beatport=,google https://www.google.com/search?q={{ printf "%s %s" .Artist .Album | urlquery }}'
      WRTAG_NOTIFICATION_URI: 'complete generic+http://music_gonic/rest/startScan.view?u=${GONIC_USER}&p=${GONIC_PASSWORD}&c=wrtag'
      WRTAG_WEB_API_KEY: ${WRTAG_WEB_API_KEY}
      GONIC_USER: ${GONIC_USER}
      GONIC_PASSWORD: ${GONIC_PASSWORD}
    ports:
      - 4848:7373
    volumes:
      - ./data/wrtag:/data
      - /mnt/music/library:/music
      - /mnt/downloads:/downloads
    restart: unless-stopped

  slskd:
    image: slskd/slskd:latest
    container_name: music_slskd
    user: 1000:1000
    ports:
      - 5030:5030
      - 50300:50300
    environment:
      SLSKD_REMOTE_CONFIGURATION: true
      SLSKD_SHARED_DIR: /music
      SLSKD_DOWNLOADS_DIR: /downloads
      SLSKD_INCOMPLETE_DIR: /downloads
      SLSKD_USERNAME: ${SLSKD_USERNAME}
      SLSKD_PASSWORD: ${SLSKD_PASSWORD}
      SLSKD_SLSK_USERNAME: ${SLSKD_SLSK_USERNAME}
      SLSKD_SLSK_PASSWORD: ${SLSKD_SLSK_PASSWORD}
      WRTAG_WEB_API_KEY: ${WRTAG_WEB_API_KEY}
    volumes:
      - ./config/slskd:/app
      - ./data/slskd:/app/data
      - /mnt/downloads:/downloads
      - /mnt/music/library:/music:ro
    restart: unless-stopped
