name: dufs

services:
  dufs:
    image: sigoden/dufs:latest
    container_name: dufs
    user: 1000:1000
    ports: 
      - 5000:5000
    volumes:
      - /mnt/data/shared:/data/shared
      - /mnt/data/syncthing/sync:/data/syncthing
    command: /data --auth ${DUFS_USER}:${DUFS_PASSWORD}
    restart: unless-stopped
