all:
  children:
    network:
      hosts:
        ts_router:
          ansible_host: 10.0.0.2
        pihole:
          ansible_host: 10.0.0.3
    vms:
      hosts:
        apps_host:
          ansible_host: 10.0.0.4
