---

- name: apply common config
  hosts: all
  roles:
    - common

- name: configure subnet router
  hosts: ts_router
  roles:
    - tailscale

- name: configure pihole
  hosts: pihole
  roles:
    - pihole

- name: configure apps host
  hosts: apps_host
  roles:
    - apps_host
    - docker
    - apps
    - docker_maintenance
    - apps_backup
