name: wrtag

services:
  wrtag:
    image: sentriz/wrtag
    container_name: wrtag
    environment:
      WRTAG_WEB_LISTEN_ADDR: ':80'
      WRTAG_WEB_PUBLIC_URL=https: //wrtag.sheol.vuxnq.me
      WRTAG_WEB_DB_PATH: /data/wrtag.db
      WRTAG_PATH_FORMAT: '/music/{{ artists .Release.Artists | join "; " | safepath }}/{{ .Release.Title | safepath }}/{{ pad0 2 .TrackNum }} {{ .Track.Title | safepath }}{{ .Ext }}'
      WRTAG_ADDON: 'lyrics genius musixmatch'
      WRTAG_COVER_UPGRADE: true
      WRTAG_WEB_API_KEY: ${WRTAG_WEB_API_KEY}
    ports:
      - 4848:80
    volumes:
      - ./data:/data
      - /mnt/music:/music
      - /mnt/downloads:/downloads
    restart: unless-stopped
