---

- name: wait for cloud-init to finish
  ansible.builtin.command: cloud-init status --wait
  changed_when: false

- name: install qemu-guest-agent
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present

- name: ensure qemu-guest-agent is enabled and running
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    state: started

- name: create filesystem on data disk
  community.general.filesystem:
    fstype: ext4
    dev: /dev/vdb

- name: mount data disk
  ansible.posix.mount:
    path: /mnt/data
    src: /dev/vdb
    fstype: ext4
    state: mounted
