branding:
  custom-footer: |
    <div>
      <a class="size-h3" href="https://github.com/vuxnq/sheol/" target="_blank">sheol</a>
      <a class="visited-indicator" href="https://github.com/glanceapp/glance/" target="_blank" rel="noreferrer">glance</a>
    </div>
  favicon-url: https://raw.githubusercontent.com/vuxnq/website/refs/heads/main/assets/favicon/favicon.ico

theme:
  contrast-multiplier: 1.2
  background-color: 240 23 9
  primary-color: 232 97 85
  positive-color: 115 54 76
  negative-color: 343 81 75

pages:
  - $include: home.yml
  - $include: news.yml
