- type: docker-containers
  hide-header: true
  containers:
    
    caddy:
      name: caddy
      icon: di:caddy
      description: web server

    dockhand:
      name: dockhand
      icon: sh:docker
      url: https://dockhand.sheol.vuxnq.me
      same-tab: true
      description: docker management

    dufs:
      name: dufs
      icon: di:files
      url: https://dufs.sheol.vuxnq.me
      same-tab: true
      description: file server

    glance:
      name: glance
      icon: sh:glance
      url: https://sheol.vuxnq.me
      same-tab: true
      description: dashboard

    immich_server:
      name: immich
      icon: sh:immich
      url: https://immich.sheol.vuxnq.me
      same-tab: true
      description: photo & video management
      id: immich
    immich_machine_learning:
      name: machine learning
      parent: immich
    immich_postgres:
      name: database
      parent: immich
    immich_redis:
      name: redis
      parent: immich

    music_navidrome:
      name: navidrome
      icon: sh:navidrome
      url: https://navidrome.sheol.vuxnq.me
      same-tab: true
      description: music streaming server
      id: music
    music_explo:
      name: explo
      parent: music
    music_explo_ofelia:
      name: explo ofelia
      parent: music

    music_slskd:
      name: slskd
      icon: sh:slskd
      url: https://slskd.sheol.vuxnq.me
      same-tab: true
      description: p2p music sharing

    music_wrtag:
      name: wrtag
      icon: sh:wrtag
      url: https://wrtag.sheol.vuxnq.me
      same-tab: true
      description: automated music tagging and organization

    pihole:
      name: pihole
      icon: sh:pi-hole
      url: https://pihole.sheol.vuxnq.me/admin
      same-tab: true
      description: network-wide ad blocking

    silverbullet:
      name: silverbullet
      icon: sh:silverbullet
      url: https://silverbullet.sheol.vuxnq.me
      same-tab: true
      description: note-taking app

    syncthing:
      name: syncthing
      icon: sh:syncthing
      url: https://syncthing.sheol.vuxnq.me
      same-tab: true
      description: continuous file synchronization

    zerobyte:
      name: zerobyte
      icon: sh:zerobyte
      url: https://zerobyte.sheol.vuxnq.me
      same-tab: true
      description: backup automation tool
