- name: home
  head-widgets:
    - type: search
      hide-header: true
      search-engine: google
      autofocus: true
      bangs:
        - title: youtube
          shortcut: "!yt"
          url: https://www.youtube.com/results?search_query={QUERY}
  columns:
    - size: small
      widgets:
        - type: clock
          hide-header: true
        - type: weather
          hide-header: true
          hour-format: 24h
          location: Ostrava, Czechia
        - type: calendar
          hide-header: true
    - size: small
      widgets:
        - type: server-stats
          hide-header: true
          servers:
            - type: local
              name: sheol
              hide-mountpoints-by-default: true
              mountpoints:
                "/":
                  name: root
                  hide: false
        - type: dns-stats
          hide-header: true
          service: pihole-v6
          url: https://pihole.sheol.vuxnq.me
          password: ${PIHOLE_PASSWORD}
        $include: home.lastfm.yml
        - type: to-do
          hide-header: true
    - size: full
      widgets:
        $include: home.bookmarks.yml
        $include: home.docker-containers.yml
