[global]
  name: copyparty
  e2dsa, e2ts, z
  au-vol: 25
  hist: /.hist
  uid: 1000
  gid: 1000

[accounts]
  # username: password

[/]
  .
  accs:
    r.: *

[/backups]
  ./backups
  accs:
    r: *
  flags:
    d2d, dthumb

[/immich]
  ./immich
  accs:
    r: *
  flags:
    d2d, dthumb

[/music]
  ./music
  accs:
    A: *
  flags:
    no-athumb, no-acode

[/dump]
  ./dump
  accs:
    A: *
  flags:
    d2d, dthumb

[/cloud]
  ./cloud
  accs:
    A: *
