name: dockhand

services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    environment:
        PUID: 1000
        PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/vuxnq/sheol:/app/data/stacks/sheol
      - ./data:/app/data
