---

- name: add tailscale's gpg key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/debian/trixie.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: "0644"

- name: add tailscale repo
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/debian/trixie.tailscale-keyring.list
    dest: /etc/apt/sources.list.d/tailscale.list
    mode: "0644"

- name: install tailscale
  ansible.builtin.apt:
    name: tailscale
    update_cache: true
    state: present

- name: enable ipv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: enable ipv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: ensure tailscaled is running and enabled
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started

- name: check current tailscale status
  ansible.builtin.command: tailscale status --json
  register: ts_status
  changed_when: false
  failed_when: false

- name: bring up tailscale
  ansible.builtin.command: >
    tailscale up
    --authkey={{ tailscale_authkey }}
    --advertise-routes={{ tailscale_advertise_routes }}
    {{ '--advertise-exit-node' if tailscale_exit_node else '' }}
  when: (ts_status.stdout | from_json).BackendState != "Running"
