ansible_python_interpreter: /usr/bin/python3

ansible_ssh_private_key_file: "~/.ssh/keys/homelab.key"
ansible_user: "root"

proxmox_user: "root"
proxmox_ip: "192.168.0.2"

ansible_ssh_common_args: "-o ProxyCommand='ssh -i {{ ansible_ssh_private_key_file }} -o StrictHostKeyChecking=accept-new -W %h:%p {{ proxmox_user }}@{{ proxmox_ip }}'"

# tailscale
tailscale_advertise_routes: "10.0.0.0/24"
tailscale_exit_node: true

# pihole
pihole_upstream_dns:
  - "1.1.1.1"
  - "1.0.0.1"

adlist_urls:
  - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.txt"
  - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/tif.txt"

# apps
apps_dir: /opt/apps
apps_services:
  - caddy
  - dockhand
  - dufs
  - glance
  - immich
  - upsnap
  - syncthing

# secrets - create 99-secrets.yml
tailscale_authkey: ""

app_secrets:
  caddy:
    PORKBUN_API_KEY: ""
    PORKBUN_API_SECRET_KEY: ""
  dufs:
    DUFS_USER: ""
    DUFS_PASSWORD: ""
  glance:
    LASTFM_API_KEY: ""
    PIHOLE_PASSWORD: ""
  immich:
    DB_USERNAME: ""
    DB_PASSWORD: ""
    DB_DATABASE_NAME: ""
  upsnap:
    SSHUSER: ""
    SSHPASS: ""
