ansible_python_interpreter: /usr/bin/python3

ansible_ssh_private_key_file: "~/.ssh/keys/homelab.key"
ansible_user: "root"

proxmox_user: "root"
proxmox_ip: "10.0.0.1"

ansible_ssh_common_args: "-o ProxyCommand='ssh -i {{ ansible_ssh_private_key_file }} -o StrictHostKeyChecking=accept-new -W %h:%p {{ proxmox_user }}@{{ proxmox_ip }}'"

ts_router_ip: "10.0.0.2"
pihole_ip: "10.0.0.3"
apps_host_ip: "10.0.0.4"

apps:
  - name: caddy
  - name: dufs
    dirs:
      - path: /mnt/data/dufs/shared
  - name: glance
  - name: immich
    backup_exclude:
      - /mnt/data/immich/postgres
      - /mnt/data/immich/ml/cache
  - name: syncthing
    dirs:
      - path: /mnt/data/syncthing
      - path: /mnt/data/syncthing/config

backup_pre_hooks:
  - "mkdir -p /mnt/data/immich && docker exec immich_postgres pg_dumpall -U {{ app_secrets.immich.DB_USERNAME }} > /mnt/data/immich/postgres-dump.sql && test -s /mnt/data/immich/postgres-dump.sql"
backup_restore_hooks:
  - "docker compose -f {{ apps_dir }}/immich/compose.yaml up -d --wait database && cat /mnt/data/immich/postgres-dump.sql | docker exec -i immich_postgres psql -U {{ app_secrets.immich.DB_USERNAME }}"

# secrets - create 99-secrets.yml
tailscale_authkey: ""

pihole_password: ""

app_secrets:
  caddy:
    PORKBUN_API_KEY: ""
    PORKBUN_API_SECRET_KEY: ""
    ACME_EMAIL: ""
  dufs:
    DUFS_USER: ""
    DUFS_PASSWORD: ""
  glance:
    LASTFM_API_KEY: ""
    PIHOLE_PASSWORD: "{{ pihole_password }}"
  immich:
    DB_USERNAME: ""
    DB_PASSWORD: ""
    DB_DATABASE_NAME: ""

backup_secrets:
  restic_password: ""
  b2_key_id: ""
  b2_application_key: ""
  b2_bucket: ""
  b2_region: ""
